openapi: "3.0.1"

info:
  title: Infernal Studios API
  version: "1.0"
  description: |
    This API facilitates the needs of Infernal Studios to provide its
    services cleanly and automatically, such as the Forge update checker,
    shortened links (redirects), etc.

    The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
    "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this
    document are to be interpreted as described in [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119).

    When the [token](#section/Authentication/token) security scheme is defined
    for a request in this doc, it means that the request must be authenticated
    with a valid token with the permission listed beside it. (Exception: the
    [POST `/auth/token`](#/paths/~1auth~1token/post) endpoint does not require any permissions)

    The following headers will always be present in responses:

    | Header | Description |
    | --- | --- |
    | X-RateLimit-Limit | The numver of allowed requests in the current period |
    | X-RateLimit-Remaining | The number of requests remaining in the current period |
    | X-RateLimit-Reset | The timestamp in seconds since the epoch of the next period |
  contact:
    name: Infernal Studios
    email: contact@infernalstudios.org
  termsOfService: https://example.com

servers:
  - url: https://infernalstudios.org/api
    description: |
      Official Infernal Studios API.
      Clients must not expect outdated versions of the API to be supported and
      served at this URL.

components:
  headers:
    $ref: ./components/headers.yml
  responses:
    $ref: ./components/responses.yml
  securitySchemes:
    $ref: ./components/securitySchemes.yml
  schemas:
    $ref: ./components/schemas.yml
  examples:
    $ref: ./components/examples.yml

paths:
  /status:
    get:
      summary: Get API status
      description: |
        Returns the status of the API. Make sure to parse the JSON response,
        and only validate the given fields, because more could be changed in
        the future.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: ["status"]
                properties:
                  status:
                    type: string
                    description: |
                      Only possible values are `"ok"` and `"maintainance"`.
                      This may change in the future.<br>
                      If this value is `"maintainance"`, the API is undergoing
                      maintainance and other endpoints should not be expected
                      to work.
                example: { "status": "ok" }
        "419":
          $ref: "#/components/responses/too_many_requests"

  /auth/login:
    $ref: "#./paths/auth/auth/login"
  /auth/token:
    $ref: "#./paths/auth/auth/token"
  /auth/token/:id:
    $ref: "#./paths/auth/auth/token/:id"
  /redirects:
    $ref: "#./paths/redirects/redirects"
  /redirects/:id:
    $ref: "#./paths/redirects/redirects/:id"
  /mods:
    $ref: "#./paths/mods/mods"
  /mods/:id:
    $ref: "#./paths/mods/mods/:id"
  /mods/:id/versions:
    $ref: "#./paths/mods/mods/:id/versions"
  /mods/:id/forge:
    $ref: "#./paths/mods/mods/:id/forge"
