openapi: "3.0.1"

info:
  title: Infernal Studios API
  version: "1.0"
  description: |
    This API facilitates the needs of Infernal Studios to provide its
    services cleanly and automatically, such as the Forge update checker,
    shortened links (redirects), etc.

    The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
    "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this
    document are to be interpreted as described in [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119).
  contact:
    name: Infernal Studios
    email: contact@infernalstudios.org
  termsOfService: https://example.com

servers:
  - url: https://infernalstudios.org/api
    description: |
      Official Infernal Studios API.
      Clients must not expect outdated versions of the API to be supported and
      served at this URL.

components:
  securitySchemes:
    login:
      type: http
      scheme: Basic
      description: |
        Basic authentication.
        This is used for generating a temporary API key for the client.

    token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        A JSON Web Token (JWT) is a compact, self-contained, signed token that
        represents an authenticated user. Read more: 
        The token is used to authenticate the user and to authorize the user's
        actions.
        The token is issued by the server and is used to identify the user.
        The token is sent in the Authorization header.

security:
  - api_key: []
paths:
  /status:
    get:
      summary: Get API status
      description: |
        Returns the status of the API. Make sure to parse the JSON response,
        and only validate the given fields, because more could be changed in
        the future.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: ["status"]
                properties:
                  status:
                    type: string
                    description: |
                      Only possible values are `"ok"` and `"maintainance"`.
                      This may change in the future.

                      If this value is `"maintainance"`, the API is undergoing
                      maintainance and other endpoints should not be expected
                      to work.
                example: { "status": "ok" }
